# automatically generated by the FlatBuffers compiler, do not modify

# namespace: vec3

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Vec3(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Vec3()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVec3(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Vec3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vec3
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Vec3
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Vec3
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Vec3Start(builder): builder.StartObject(3)
def Start(builder):
    return Vec3Start(builder)
def Vec3AddX(builder, x): builder.PrependFloat32Slot(0, x, 0.0)
def AddX(builder, x):
    return Vec3AddX(builder, x)
def Vec3AddY(builder, y): builder.PrependFloat32Slot(1, y, 0.0)
def AddY(builder, y):
    return Vec3AddY(builder, y)
def Vec3AddZ(builder, z): builder.PrependFloat32Slot(2, z, 0.0)
def AddZ(builder, z):
    return Vec3AddZ(builder, z)
def Vec3End(builder): return builder.EndObject()
def End(builder):
    return Vec3End(builder)