# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ContainsNamespaced(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContainsNamespaced()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContainsNamespaced(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ContainsNamespaced
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContainsNamespaced
    def Inside(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from flattrs_test.nested.NestedJustAString import NestedJustAString
            obj = NestedJustAString()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ContainsNamespacedStart(builder): builder.StartObject(1)
def Start(builder):
    return ContainsNamespacedStart(builder)
def ContainsNamespacedAddInside(builder, inside): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(inside), 0)
def AddInside(builder, inside):
    return ContainsNamespacedAddInside(builder, inside)
def ContainsNamespacedEnd(builder): return builder.EndObject()
def End(builder):
    return ContainsNamespacedEnd(builder)