# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JustAFloat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JustAFloat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJustAFloat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # JustAFloat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JustAFloat
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def JustAFloatStart(builder): builder.StartObject(1)
def Start(builder):
    return JustAFloatStart(builder)
def JustAFloatAddValue(builder, value): builder.PrependFloat32Slot(0, value, 0.0)
def AddValue(builder, value):
    return JustAFloatAddValue(builder, value)
def JustAFloatEnd(builder): return builder.EndObject()
def End(builder):
    return JustAFloatEnd(builder)