# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NumberedUnionTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NumberedUnionTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNumberedUnionTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NumberedUnionTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NumberedUnionTable
    def InnerUnionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # NumberedUnionTable
    def InnerUnion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def NumberedUnionTableStart(builder): builder.StartObject(2)
def Start(builder):
    return NumberedUnionTableStart(builder)
def NumberedUnionTableAddInnerUnionType(builder, innerUnionType): builder.PrependUint8Slot(0, innerUnionType, 0)
def AddInnerUnionType(builder, innerUnionType):
    return NumberedUnionTableAddInnerUnionType(builder, innerUnionType)
def NumberedUnionTableAddInnerUnion(builder, innerUnion): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(innerUnion), 0)
def AddInnerUnion(builder, innerUnion):
    return NumberedUnionTableAddInnerUnion(builder, innerUnion)
def NumberedUnionTableEnd(builder): return builder.EndObject()
def End(builder):
    return NumberedUnionTableEnd(builder)