# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OptionalSeqVectorOfStrings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OptionalSeqVectorOfStrings()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOptionalSeqVectorOfStrings(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OptionalSeqVectorOfStrings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OptionalSeqVectorOfStrings
    def Strings(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # OptionalSeqVectorOfStrings
    def StringsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OptionalSeqVectorOfStrings
    def StringsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def OptionalSeqVectorOfStringsStart(builder): builder.StartObject(1)
def Start(builder):
    return OptionalSeqVectorOfStringsStart(builder)
def OptionalSeqVectorOfStringsAddStrings(builder, strings): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(strings), 0)
def AddStrings(builder, strings):
    return OptionalSeqVectorOfStringsAddStrings(builder, strings)
def OptionalSeqVectorOfStringsStartStringsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartStringsVector(builder, numElems):
    return OptionalSeqVectorOfStringsStartStringsVector(builder, numElems)
def OptionalSeqVectorOfStringsEnd(builder): return builder.EndObject()
def End(builder):
    return OptionalSeqVectorOfStringsEnd(builder)