# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OptVectorOfEnums(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OptVectorOfEnums()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOptVectorOfEnums(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # OptVectorOfEnums
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OptVectorOfEnums
    def Enums(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # OptVectorOfEnums
    def EnumsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # OptVectorOfEnums
    def EnumsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OptVectorOfEnums
    def EnumsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def OptVectorOfEnumsStart(builder): builder.StartObject(1)
def Start(builder):
    return OptVectorOfEnumsStart(builder)
def OptVectorOfEnumsAddEnums(builder, enums): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(enums), 0)
def AddEnums(builder, enums):
    return OptVectorOfEnumsAddEnums(builder, enums)
def OptVectorOfEnumsStartEnumsVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartEnumsVector(builder, numElems):
    return OptVectorOfEnumsStartEnumsVector(builder, numElems)
def OptVectorOfEnumsEnd(builder): return builder.EndObject()
def End(builder):
    return OptVectorOfEnumsEnd(builder)