# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VectorOfEnums(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VectorOfEnums()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVectorOfEnums(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VectorOfEnums
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VectorOfEnums
    def Enums(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # VectorOfEnums
    def EnumsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # VectorOfEnums
    def EnumsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VectorOfEnums
    def EnumsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def VectorOfEnumsStart(builder): builder.StartObject(1)
def Start(builder):
    return VectorOfEnumsStart(builder)
def VectorOfEnumsAddEnums(builder, enums): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(enums), 0)
def AddEnums(builder, enums):
    return VectorOfEnumsAddEnums(builder, enums)
def VectorOfEnumsStartEnumsVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartEnumsVector(builder, numElems):
    return VectorOfEnumsStartEnumsVector(builder, numElems)
def VectorOfEnumsEnd(builder): return builder.EndObject()
def End(builder):
    return VectorOfEnumsEnd(builder)