# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers

class Common1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCommon1(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Common1()
        x.Init(buf, n + offset)
        return x

    # Common1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Common1
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # Common1
    def ASmallInt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Common1
    def ABigInt(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Common1Start(builder): builder.StartObject(3)
def Common1AddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def Common1AddASmallInt(builder, aSmallInt): builder.PrependUint8Slot(1, aSmallInt, 0)
def Common1AddABigInt(builder, aBigInt): builder.PrependInt32Slot(2, aBigInt, 0)
def Common1End(builder): return builder.EndObject()
