# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers

class JustAString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsJustAString(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JustAString()
        x.Init(buf, n + offset)
        return x

    # JustAString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JustAString
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

def JustAStringStart(builder): builder.StartObject(1)
def JustAStringAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def JustAStringEnd(builder): return builder.EndObject()
