# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers

class JustADouble(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsJustADouble(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JustADouble()
        x.Init(buf, n + offset)
        return x

    # JustADouble
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JustADouble
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def JustADoubleStart(builder): builder.StartObject(1)
def JustADoubleAddValue(builder, value): builder.PrependFloat64Slot(0, value, 0.0)
def JustADoubleEnd(builder): return builder.EndObject()
