# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers

class ListOfStrings(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsListOfStrings(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ListOfStrings()
        x.Init(buf, n + offset)
        return x

    # ListOfStrings
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ListOfStrings
    def Content(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # ListOfStrings
    def ContentLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def ListOfStringsStart(builder): builder.StartObject(1)
def ListOfStringsAddContent(builder, content): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(content), 0)
def ListOfStringsStartContentVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ListOfStringsEnd(builder): return builder.EndObject()
