# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers


class SeqVectorOfOptionalCommon1(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsSeqVectorOfOptionalCommon1(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SeqVectorOfOptionalCommon1()
        x.Init(buf, n + offset)
        return x

    # SeqVectorOfOptionalCommon1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SeqVectorOfOptionalCommon1
    def VecOfCommon(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Common1 import Common1

            obj = Common1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SeqVectorOfOptionalCommon1
    def VecOfCommonLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0


def SeqVectorOfOptionalCommon1Start(builder):
    builder.StartObject(1)


def SeqVectorOfOptionalCommon1AddVecOfCommon(builder, vecOfCommon):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfCommon), 0
    )


def SeqVectorOfOptionalCommon1StartVecOfCommonVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def SeqVectorOfOptionalCommon1End(builder):
    return builder.EndObject()
