# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers


class SeqVectorOfEnums(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsSeqVectorOfEnums(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SeqVectorOfEnums()
        x.Init(buf, n + offset)
        return x

    # SeqVectorOfEnums
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SeqVectorOfEnums
    def Enums(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(
                flatbuffers.number_types.Uint8Flags,
                a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1),
            )
        return 0

    # SeqVectorOfEnums
    def EnumsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SeqVectorOfEnums
    def EnumsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0


def SeqVectorOfEnumsStart(builder):
    builder.StartObject(1)


def SeqVectorOfEnumsAddEnums(builder, enums):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(enums), 0
    )


def SeqVectorOfEnumsStartEnumsVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)


def SeqVectorOfEnumsEnd(builder):
    return builder.EndObject()
