# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FrozenTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FrozenTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFrozenTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FrozenTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FrozenTable
    def AString(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def FrozenTableStart(builder): builder.StartObject(1)
def Start(builder):
    return FrozenTableStart(builder)
def FrozenTableAddAString(builder, aString): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(aString), 0)
def AddAString(builder, aString):
    return FrozenTableAddAString(builder, aString)
def FrozenTableEnd(builder): return builder.EndObject()
def End(builder):
    return FrozenTableEnd(builder)