# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

class NumberedUnion(object):
    NONE = 0
    AllScalars = 1
    Common1 = 100
    AllScalarsWithDefaults = 101
