# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flattrs_test

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SingleClassUnionRequiredTable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SingleClassUnionRequiredTable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSingleClassUnionRequiredTable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SingleClassUnionRequiredTable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SingleClassUnionRequiredTable
    def SingleClassReqUnionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SingleClassUnionRequiredTable
    def SingleClassReqUnion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def SingleClassUnionRequiredTableStart(builder): builder.StartObject(2)
def Start(builder):
    return SingleClassUnionRequiredTableStart(builder)
def SingleClassUnionRequiredTableAddSingleClassReqUnionType(builder, singleClassReqUnionType): builder.PrependUint8Slot(0, singleClassReqUnionType, 0)
def AddSingleClassReqUnionType(builder, singleClassReqUnionType):
    return SingleClassUnionRequiredTableAddSingleClassReqUnionType(builder, singleClassReqUnionType)
def SingleClassUnionRequiredTableAddSingleClassReqUnion(builder, singleClassReqUnion): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(singleClassReqUnion), 0)
def AddSingleClassReqUnion(builder, singleClassReqUnion):
    return SingleClassUnionRequiredTableAddSingleClassReqUnion(builder, singleClassReqUnion)
def SingleClassUnionRequiredTableEnd(builder): return builder.EndObject()
def End(builder):
    return SingleClassUnionRequiredTableEnd(builder)