# automatically generated by the FlatBuffers compiler, do not modify

# namespace: nested

import flatbuffers

class NestedJustAString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNestedJustAString(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NestedJustAString()
        x.Init(buf, n + offset)
        return x

    # NestedJustAString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NestedJustAString
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def NestedJustAStringStart(builder): builder.StartObject(1)
def NestedJustAStringAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def NestedJustAStringEnd(builder): return builder.EndObject()
