# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SeqVectorsOfScalars(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SeqVectorsOfScalars()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSeqVectorsOfScalars(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SeqVectorsOfScalars
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SeqVectorsOfScalars
    def VecOfBools(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SeqVectorsOfScalars
    def VecOfBoolsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfBoolsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfBoolsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfUint8s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SeqVectorsOfScalars
    def VecOfUint8sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint8sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint8sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfUint16s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # SeqVectorsOfScalars
    def VecOfUint16sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint16Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint16sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint16sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfUint32s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SeqVectorsOfScalars
    def VecOfUint32sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint32sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint32sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfUint64s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # SeqVectorsOfScalars
    def VecOfUint64sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint64sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfUint64sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfInt8s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # SeqVectorsOfScalars
    def VecOfInt8sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int8Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt8sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt8sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfInt16s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int16Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 2))
        return 0

    # SeqVectorsOfScalars
    def VecOfInt16sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int16Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt16sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt16sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfInt32s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SeqVectorsOfScalars
    def VecOfInt32sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt32sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt32sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfInt64s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # SeqVectorsOfScalars
    def VecOfInt64sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt64sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfInt64sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfFloat32s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # SeqVectorsOfScalars
    def VecOfFloat32sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfFloat32sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfFloat32sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # SeqVectorsOfScalars
    def VecOfFloat64s(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # SeqVectorsOfScalars
    def VecOfFloat64sAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # SeqVectorsOfScalars
    def VecOfFloat64sLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SeqVectorsOfScalars
    def VecOfFloat64sIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def SeqVectorsOfScalarsStart(builder): builder.StartObject(11)
def Start(builder):
    return SeqVectorsOfScalarsStart(builder)
def SeqVectorsOfScalarsAddVecOfBools(builder, vecOfBools): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfBools), 0)
def AddVecOfBools(builder, vecOfBools):
    return SeqVectorsOfScalarsAddVecOfBools(builder, vecOfBools)
def SeqVectorsOfScalarsStartVecOfBoolsVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartVecOfBoolsVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfBoolsVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfUint8s(builder, vecOfUint8s): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfUint8s), 0)
def AddVecOfUint8s(builder, vecOfUint8s):
    return SeqVectorsOfScalarsAddVecOfUint8s(builder, vecOfUint8s)
def SeqVectorsOfScalarsStartVecOfUint8sVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartVecOfUint8sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfUint8sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfUint16s(builder, vecOfUint16s): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfUint16s), 0)
def AddVecOfUint16s(builder, vecOfUint16s):
    return SeqVectorsOfScalarsAddVecOfUint16s(builder, vecOfUint16s)
def SeqVectorsOfScalarsStartVecOfUint16sVector(builder, numElems): return builder.StartVector(2, numElems, 2)
def StartVecOfUint16sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfUint16sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfUint32s(builder, vecOfUint32s): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfUint32s), 0)
def AddVecOfUint32s(builder, vecOfUint32s):
    return SeqVectorsOfScalarsAddVecOfUint32s(builder, vecOfUint32s)
def SeqVectorsOfScalarsStartVecOfUint32sVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartVecOfUint32sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfUint32sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfUint64s(builder, vecOfUint64s): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfUint64s), 0)
def AddVecOfUint64s(builder, vecOfUint64s):
    return SeqVectorsOfScalarsAddVecOfUint64s(builder, vecOfUint64s)
def SeqVectorsOfScalarsStartVecOfUint64sVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def StartVecOfUint64sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfUint64sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfInt8s(builder, vecOfInt8s): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfInt8s), 0)
def AddVecOfInt8s(builder, vecOfInt8s):
    return SeqVectorsOfScalarsAddVecOfInt8s(builder, vecOfInt8s)
def SeqVectorsOfScalarsStartVecOfInt8sVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartVecOfInt8sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfInt8sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfInt16s(builder, vecOfInt16s): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfInt16s), 0)
def AddVecOfInt16s(builder, vecOfInt16s):
    return SeqVectorsOfScalarsAddVecOfInt16s(builder, vecOfInt16s)
def SeqVectorsOfScalarsStartVecOfInt16sVector(builder, numElems): return builder.StartVector(2, numElems, 2)
def StartVecOfInt16sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfInt16sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfInt32s(builder, vecOfInt32s): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfInt32s), 0)
def AddVecOfInt32s(builder, vecOfInt32s):
    return SeqVectorsOfScalarsAddVecOfInt32s(builder, vecOfInt32s)
def SeqVectorsOfScalarsStartVecOfInt32sVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartVecOfInt32sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfInt32sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfInt64s(builder, vecOfInt64s): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfInt64s), 0)
def AddVecOfInt64s(builder, vecOfInt64s):
    return SeqVectorsOfScalarsAddVecOfInt64s(builder, vecOfInt64s)
def SeqVectorsOfScalarsStartVecOfInt64sVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def StartVecOfInt64sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfInt64sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfFloat32s(builder, vecOfFloat32s): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfFloat32s), 0)
def AddVecOfFloat32s(builder, vecOfFloat32s):
    return SeqVectorsOfScalarsAddVecOfFloat32s(builder, vecOfFloat32s)
def SeqVectorsOfScalarsStartVecOfFloat32sVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartVecOfFloat32sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfFloat32sVector(builder, numElems)
def SeqVectorsOfScalarsAddVecOfFloat64s(builder, vecOfFloat64s): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(vecOfFloat64s), 0)
def AddVecOfFloat64s(builder, vecOfFloat64s):
    return SeqVectorsOfScalarsAddVecOfFloat64s(builder, vecOfFloat64s)
def SeqVectorsOfScalarsStartVecOfFloat64sVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def StartVecOfFloat64sVector(builder, numElems):
    return SeqVectorsOfScalarsStartVecOfFloat64sVector(builder, numElems)
def SeqVectorsOfScalarsEnd(builder): return builder.EndObject()
def End(builder):
    return SeqVectorsOfScalarsEnd(builder)